### ISSUE TITLE
Documentation is broken

### ISSUE THREAD

**Issue by florianjehn** [allfed/Seaweed-Growth-Model#20]
All things point to 404

**Comment by Recktenwald** [comment]
Cannot reproduce 
https://allfed.github.io/Seaweed-Growth-Model/modules/src/model/seaweed_growth/
seems to not 404 anymore

**Comment by florianjehn** [comment]
That's odd. I have changed nothing :sweat_smile: 
But yeah, seems to be working again. Strange.
